<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('employees')->insert([
            [
                'id' => 1,
                'employee_code' => 1,
                'fp_code' => 12,
                'name' => 'سها السيد محمود خليل',
                'gender' => 'Female',
                'branch_id' => 1,
                'qualification_id' => 6,
                'qualification_year' => '1990',
                'major' => 'Ex quia perspiciatis',
                'graduation_estimate' => 'Excellent',
                'brith_date' => '1970-08-04',
                'national_id' => '123456789',
                'end_national_id' => '1996-04-23',
                'national_id_place' => 'بولاق الدكرور',
                'blood_types_id' => 2,
                'religion' => 'Muslim',
                'language_id' => 1,
                'email' => 'fupaha@mailinator.com',
                'country_id' => 1,
                'governorate_id' => 1,
                'city_id' => 1,
                'home_telephone' => '0225789512',
                'work_telephone' => '0224782512',
                'mobile' => '01550989855',
                'military' => 'Exemption',
                'military_exemption_date' => '2011-07-09',
                'military_exemption_reason' => 'أنثى',
                'driving_license' => 'No',
                'work_start_date' => '2019-09-17',
                'functional_status' => 'Employee',
                'department_id' => 2,
                'job_categories_id' => 6,
                'has_attendance' => 'Yes',
                'has_fixed_shift' => 'Yes',
                'shift_types_id' => 1,
                'salary' => '5000.00',
                'motivation_type' => 'Fixed',
                'motivation' => '500.00',
                'social_insurance' => 'Yes',
                'social_insurance_cut_monthely' => '500.00',
                'social_insurance_number' => '8755488999',
                'medical_insurance' => 'Yes',
                'medical_insurance_number' => 'Visa',
                'active_vacation' => 'Yes',
                'urgent_person_details' => 'احمد السيد ذكى - 01110050006',
                'staies_address' => '8 شارع ابن خلدون السبتية',
                'children_number' => 4,
                'social_status' => 'Married',
                'nationality_id' => 1,
                'name_sponsor' => 'احمد محمود',
                'pasport_identity' => '1518151020551',
                'pasport_from_place' => 'Ipsum incidunt in',
                'pasport_exp_date' => '1995-03-09',
                'day_price' => '170.00',
                'created_by' => 1,
                'com_code'=>1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'employee_code' => 2,
                'fp_code' => 13,
                'name' => 'محمود احمد عبدالحميد على',
                'gender' => 'Male',
                'branch_id' => 3,
                'qualification_id' => 4,
                'qualification_year' => '1990',
                'major' => 'تجارة خارجيه',
                'graduation_estimate' => 'Excellent',
                'brith_date' => '1980-08-04',
                'national_id' => '123456449',
                'end_national_id' => '1996-04-23',
                'national_id_place' => 'م نصر',
                'blood_types_id' => 4,
                'religion' => 'Muslim',
                'language_id' => 1,
                'email' => 'mahmouda@mailinator.com',
                'country_id' => 1,
                'governorate_id' => 1,
                'city_id' => 3,
                'home_telephone' => '024155212',
                'work_telephone' => '022402212',
                'mobile' => '01548189855',
                'military' => 'Exemption',
                'military_exemption_date' => '2011-07-09',
                'military_exemption_reason' => 'وحيد الاخوات',
                'driving_license' => 'No',
                'work_start_date' => '2019-09-17',
                'functional_status' => 'Employee',
                'department_id' => 2,
                'job_categories_id' => 6,
                'has_attendance' => 'Yes',
                'has_fixed_shift' => 'Yes',
                'shift_types_id' => 1,
                'salary' => '8000.00',
                'motivation_type' => 'Fixed',
                'motivation' => '500.00',
                'social_insurance' => 'Yes',
                'social_insurance_cut_monthely' => '500.00',
                'social_insurance_number' => '870008598',
                'medical_insurance' => 'Yes',
                'medical_insurance_number' => 'Visa',
                'active_vacation' => 'Yes',
                'urgent_person_details' => 'منال ابراهيم عبدالرازق - 01110050006',
                'staies_address' => '13 أ شارع عطالله بولاق الدكرور',
                'children_number' => 3,
                'social_status' => 'Widowed',
                'nationality_id' => 1,
                'name_sponsor' => 'احمد محمود',
                'pasport_identity' => '1518151020551',
                'pasport_from_place' => 'Ipsum incidunt in',
                'pasport_exp_date' => '1995-03-09',
                'day_price' => '270.00',
                'created_by' => 1,
                'com_code' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}
