<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class FinanceClnPeriodsSeeder extends Seeder
{
    public function run()
    {
        DB::table('finance_cln_periods')->insert([
            [
                'id' => 1,
                'finance_calendars_id' => 1,
                'finance_yr' => '2025',
                'month_id' => 1,
                'year_and_month' => '2025-01',
                'start_date_m' => '2025-01-01',
                'end_date_m' => '2025-01-31',
                'number_of_days' => 31,
                'start_date_fp' => '2025-01-01',
                'end_date_fp' => '2025-01-31',
                'is_open' => 0,
                'created_by' => '1',
                'updated_by' => '1',
                'com_code' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Add other records similarly...
            // Example:
            [
                'id' => 2,
                'finance_calendars_id' => 1,
                'finance_yr' => '2025',
                'month_id' => 2,
                'year_and_month' => '2025-02',
                'start_date_m' => '2025-02-01',
                'end_date_m' => '2025-02-28',
                'number_of_days' => 28,
                'start_date_fp' => '2025-02-01',
                'end_date_fp' => '2025-02-28',
                'is_open' => 0,
                'created_by' => '1',
                'updated_by' => '1',
                'com_code' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Repeat for remaining months...
            [
                'id' => 3,
                'finance_calendars_id' => 1,
                'finance_yr' => '2025',
                'month_id' => 3,
                'year_and_month' => '2025-03',
                'start_date_m' => '2025-03-01',
                'end_date_m' => '2025-03-31',
                'number_of_days' => 31,
                'start_date_fp' => '2025-03-01',
                'end_date_fp' => '2025-03-31',
                'is_open' => 0,
                'created_by' => '1',
                'updated_by' => '1',
                'com_code' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'id' => 4,
                'finance_calendars_id' => 1,
                'finance_yr' => '2025',
                'month_id' => 4,
                'year_and_month' => '2025-04',
                'start_date_m' => '2025-04-01',
                'end_date_m' => '2025-04-30',
                'number_of_days' => 30,
                'start_date_fp' => '2025-04-01',
                'end_date_fp' => '2025-04-30',
                'is_open' => 0,
                'created_by' => '1',
                'updated_by' => '1',
                'com_code' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'id' => 5,
                'finance_calendars_id' => 1,
                'finance_yr' => '2025',
                'month_id' => 5,
                'year_and_month' => '2025-05',
                'start_date_m' => '2025-05-01',
                'end_date_m' => '2025-05-31',
                'number_of_days' => 31,
                'start_date_fp' => '2025-05-01',
                'end_date_fp' => '2025-05-31',
                'is_open' => 0,
                'created_by' => '1',
                'updated_by' => '1',
                'com_code' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'id' => 6,
                'finance_calendars_id' => 1,
                'finance_yr' => '2025',
                'month_id' => 6,
                'year_and_month' => '2025-06',
                'start_date_m' => '2025-06-01',
                'end_date_m' => '2025-06-30',
                'number_of_days' => 30,
                'start_date_fp' => '2025-06-01',
                'end_date_fp' => '2025-06-30',
                'is_open' => 0,
                'created_by' => '1',
                'updated_by' => '1',
                'com_code' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'id' => 7,
                'finance_calendars_id' => 1,
                'finance_yr' => '2025',
                'month_id' => 7,
                'year_and_month' => '2025-07',
                'start_date_m' => '2025-07-01',
                'end_date_m' => '2025-07-31',
                'number_of_days' => 31,
                'start_date_fp' => '2025-07-01',
                'end_date_fp' => '2025-07-31',
                'is_open' => 0,
                'created_by' => '1',
                'updated_by' => '1',
                'com_code' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'id' => 8,
                'finance_calendars_id' => 1,
                'finance_yr' => '2025',
                'month_id' => 8,
                'year_and_month' => '2025-08',
                'start_date_m' => '2025-08-01',
                'end_date_m' => '2025-08-31',
                'number_of_days' => 31,
                'start_date_fp' => '2025-08-01',
                'end_date_fp' => '2025-08-31',
                'is_open' => 0,
                'created_by' => '1',
                'updated_by' => '1',
                'com_code' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'id' => 9,
                'finance_calendars_id' => 1,
                'finance_yr' => '2025',
                'month_id' => 9,
                'year_and_month' => '2025-09',
                'start_date_m' => '2025-09-01',
                'end_date_m' => '2025-09-30',
                'number_of_days' => 30,
                'start_date_fp' => '2025-09-01',
                'end_date_fp' => '2025-09-30',
                'is_open' => 0,
                'created_by' => '1',
                'updated_by' => '1',
                'com_code' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'id' => 10,
                'finance_calendars_id' => 1,
                'finance_yr' => '2025',
                'month_id' => 10,
                'year_and_month' => '2025-10',
                'start_date_m' => '2025-10-01',
                'end_date_m' => '2025-10-31',
                'number_of_days' => 31,
                'start_date_fp' => '2025-10-01',
                'end_date_fp' => '2025-10-31',
                'is_open' => 0,
                'created_by' => '1',
                'updated_by' => '1',
                'com_code' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'id' => 11,
                'finance_calendars_id' => 1,
                'finance_yr' => '2025',
                'month_id' => 11,
                'year_and_month' => '2025-11',
                'start_date_m' => '2025-11-01',
                'end_date_m' => '2025-11-30',
                'number_of_days' => 30,
                'start_date_fp' => '2025-11-01',
                'end_date_fp' => '2025-11-30',
                'is_open' => 0,
                'created_by' => '1',
                'updated_by' => '1',
                'com_code' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'id' => 12,
                'finance_calendars_id' => 1,
                'finance_yr' => '2025',
                'month_id' => 12,
                'year_and_month' => '2025-02',
                'start_date_m' => '2025-12-01',
                'end_date_m' => '2025-12-31',
                'number_of_days' => 31,
                'start_date_fp' => '2025-12-01',
                'end_date_fp' => '2025-12-30',
                'is_open' => 0,
                'created_by' => '1',
                'updated_by' => '1',
                'com_code' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

        ]);
    }
}